### ISSUE TITLE
kdb callback not working

### ISSUE THREAD

**Issue by ajayrathore** [redsift/rkdb#14]
Hi,
I am trying to call a q function from within a rust function as follows. I basically added this function to the embed crate in demo 

Running on macos

```
#[no_mangle]
pub extern "C" fn test_callback(_: *const K) -> *const K {
    println!("test_callback");
    unsafe {
            for i in 1..5 {
                println!("looping");
                k(0, ffi::CString::new("callback".as_bytes().to_vec()).unwrap().as_ptr(), 0);
            }
    }
    kvoid()
}
```

When i call it from q, it does not seem to call "callback" function

```
q)test_callback: `libembed 2:(`test_callback;1)
q)callback:{[x] show "callback..."; show x}
q)test_callback[`]
test_callback
looping
looping
looping
looping
q)
```
Is it something not supported yet? This is a minitiarized version of what I am trying to do.

**Comment by ajayrathore** [comment]
It seems to work if I call k like this
```
k(0, ffi::CString::new("callback[]".as_bytes().to_vec()).unwrap().as_ptr(), 0, 0)
```


in q
```
q)callback:{[x] show "callback......."}
q)
q)test_callback[`]
test_callback
looping
"callback......."
looping
"callback......."
looping
"callback......."
looping
"callback......."
q)
```

But question now is how would I pass any parameters?

**Comment by ajayrathore** [comment]
Seems like I missed passing the parameter in k format, the following works alright.

k(0, ffi::CString::new("callback".as_bytes().to_vec()).unwrap().as_ptr(), kj(0), 0)

closing the issue now.

**Comment by rsdy** [comment]
Thanks for trying this. I'll close the issue since it seems like a gotcha. We don't actually do this for our internal application, so it's useful that you tried it.

**Comment by ajayrathore** [comment]
Apologies for the noise.
Btw, good job on the library!!

On a separate note, how does it handle a list of symbols passed from kdb? I have a simple function which results in seg fault

```
#[no_mangle]
pub extern "C" fn ksymbols(k: *const K) -> *const K {
    match KVal::new(k) {
        KVal::Symbol(KData::List(s)) => println!("Symbols received {:?}", s),
        _ => println!("no symbols"),
    }
    kvoid()
}

q)ksymbols[`a`b`c`d]
thread '<unnamed>' panicked at 'byte index 80 is not a char boundary; it is inside '\u{0}' (bytes 79..80) of `aC[��������lj��
��������ljfN�Z�5`���������aj>gGf��p���������.Q.fl�eGf��������.Q.ff�^���������.Q.ajf0����������g����������`[...]', src/libcore/str/mod.rs:2154:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
q: warning: q crashed, killed by SIGABRT.
q itself has not crashed, but for transparency,
it will now kill itself (without dumping core) with the same signal
```

It looks like its something to do with null terminated strings, and could be solved by ffi:CStr? 
I dont see any example in the demo which handles list of syms passed in from kdb.
